language: python
python:
    - "3.8"
before_install:
    - python -m pip install --upgrade pip
install:
    - pip install -r requirements.txt
script:
    - python -m pytest --cov=./src/ tests/
    - python -m coverage report --fail-under=80
branches:
    only:
        - master
        - staging
        - qa
        - dev
